### ISSUE TITLE
Website: Nav Component link for '/pricing' is broken

### ISSUE THREAD

**Issue by chris-talke-canopi** [LimeJourney/limeJourney#33]
Came across LimeJourney on HN, found that the `/pricing` link in the Nav component for the website is broken.

https://github.com/LimeJourney/limeJourney/blob/ff6d48506d26a23436024c1e53c73caceac8765d/apps/web/src/components/nav.tsx#L36

**Comment by Ghvstcode** [comment]
Hey, great catch. Thank you. This is fixed now.
